# Generated by Django 6.0.2 on 2026-02-27 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vuelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField(unique=True)),
                (
                    "aerolinea",
                    models.CharField(
                        choices=[
                            ("Avianca", "Avianca"),
                            ("Latam", "Latam"),
                            ("Viva Air", "Viva Air"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("Bogota", "Bogotá"),
                            ("Medellin", "Medellín"),
                            ("Cali", "Cali"),
                            ("Bucaramanga", "Bucaramanga"),
                            ("Cartagena", "Cartagena"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        choices=[
                            ("Bogota", "Bogotá"),
                            ("Medellin", "Medellín"),
                            ("Cali", "Cali"),
                            ("Bucaramanga", "Bucaramanga"),
                            ("Cartagena", "Cartagena"),
                        ],
                        max_length=32,
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_salida", models.TimeField()),
                ("duracion", models.IntegerField(help_text="Duración en horas")),
                ("precio_minimo", models.FloatField()),
                ("precio_maximo", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "Vuelos",
                "ordering": ["fecha", "hora_salida"],
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_reserva",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("nombre_pasajero", models.CharField(max_length=120)),
                ("num_personas", models.IntegerField(default=1)),
                (
                    "tipo_equipaje",
                    models.CharField(
                        choices=[
                            ("mano", "Equipaje de Mano"),
                            ("bodega", "Equipaje de Bodega"),
                        ],
                        max_length=10,
                    ),
                ),
                ("precio_sugerido", models.FloatField()),
                ("precio_final", models.FloatField()),
                (
                    "metodo_pago",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("credito", "Tarjeta de Crédito"),
                            ("debito", "Tarjeta Débito"),
                            ("pse", "PSE"),
                            ("efectivo", "Efectivo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_reserva", models.DateTimeField(auto_now_add=True)),
                (
                    "vuelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="vuelos.vuelo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reservas",
                "ordering": ["-fecha_reserva"],
            },
        ),
    ]
